### ISSUE TITLE
Error when rendering formulas in Firefox browser

### ISSUE THREAD

**Issue by Mariede** [mehdisadeghi/react-mathjax-preview#78] opened 2022-05-05 14:45 UTC
Hi there.

I am using react-mathjax-preview component to draw some formulas in html pages but, unfortunatelly, I found some problems specifically when rendering them at Firefox browser. There are two errors:

* first to pop
> window.chrome is undefined

* second to pop
> this.queue is undefined

The second error is catched and displayed on screen by Error Boundaries (I guess they may be related), as the image bellow shows

![image](https://user-images.githubusercontent.com/4501798/166943859-316e5ec2-17a8-463c-9b73-d54c00c9225b.png)

But it works totally fine in Chrome/Edge

![image](https://user-images.githubusercontent.com/4501798/166944594-fe90ab02-a98f-4165-ad9e-16f7d0484e6e.png)

I'm using React 17 and react-mathjax-preview 2.2.6, nothing exceptional. Code as example:

```
...
  <MathJax
	  math={
		`\`${' ... '}\``
	  }
	  msDelayDisplay={ mathJaxMsDelayedDisplay }
  />
...
```

Thank's for any help! Regards.

**Comment by mehdisadeghi** [comment] 2022-05-06 07:37
The [demo page](https://mehdisadeghi.github.io/react-mathjax-preview/) works just fine in Firefox 99 for me. Does it work for you?

**Comment by Mariede** [comment] 2022-05-06 14:58
Hey. I am traveling and can't check it right now. As soon as possible I will give you a feedback ok.

Thank you!

**Comment by Mariede** [comment] 2022-05-13 03:49
Hey, I just tested the demo page and sadly found the same error... as showed bellow:

![image](https://user-images.githubusercontent.com/4501798/168206853-2fac04d4-db16-4d6e-a736-ec35ee1516a3.png)

I am using this version:

![image](https://user-images.githubusercontent.com/4501798/168207001-ddc6996d-f70a-4a1e-b198-00d8d954d7c6.png)


I remember to see this error already at 9x... Right now I can't figure what may have caused this.

**Comment by Mariede** [comment] 2022-05-13 17:17
Ok. I found the problem. It is an installed extension in my machine, specifically this one:

![image](https://user-images.githubusercontent.com/4501798/168334610-684c9689-c9bf-46eb-b6b8-d6008396d4b2.png)

Disabling it and everything goes fine and smooth....

I will uninstall it, since I am not even using it anymore lol

Sorry for that mate. I will close the issue soon.

Michel

**Comment by mehdisadeghi** [comment] 2022-05-13 19:33
Glad you found the cause. I close the issue, feel free to reopen if you experience the error without the extension.

**Closed as completed by mehdisadeghi** 2022-05-13 19:33 UTC
