### ISSUE TITLE
Taking only single space and whenever there is fraction in latex it reduces the font size.

### ISSUE THREAD

**Issue by karnprem90** [mehdisadeghi/react-mathjax-preview#4] opened 2017-11-02 05:58 UTC

**Comment by mehdisadeghi** [comment] 2017-11-02 09:11
Please explain how I can reproduce this problem.

**Comment by karnprem90** [comment] 2017-11-02 11:01
Or basically start sentence after pressing two spaces or more in editor then it removes the space during parsing. And another if you will paste any fraction latex equation you will see it reduces the font size comparison to other latex equation font size.

**Comment by karnprem90** [comment] 2017-11-03 22:02
![screen shot 2017-11-04 at 3 31 04 am](https://user-images.githubusercontent.com/9381098/32397626-abf9d11e-c110-11e7-8aa5-f110fee1720e.png)

I am attaching the image. I just cloned repo and run it locally. You will see the font size is very small for fraction equation.

**Comment by mehdisadeghi** [comment] 2017-11-15 10:07
Please try your input against [MathJax demo](https://www.mathjax.org). If MathJax is able to produce what you need we can also add it to the react wrapper.

**Comment by mehdisadeghi** [comment] 2019-11-12 06:34
Closing since this is default MathJax behaviour. See [Demo](https://www.mathjax.org/#demo) and feel free to reopen.

**Closed as completed by mehdisadeghi** 2019-11-12 06:34 UTC
