### ISSUE TITLE
Error on setting 'loading: true' state

### ISSUE THREAD

**Issue by Exelenz9** [mehdisadeghi/react-mathjax-preview#5] opened 2017-11-03 11:42 UTC
Hi, I'm getting an error while initial loading a page with react-mathjax-preview. The error message:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the _default component.

It refers to the line https://github.com/mehdisadeghi/react-mathjax-preview/blob/master/src/index.js#L28

Here is my component code, where I use mathjax:

```javascript
import React, { Component } from "react";
import MathJax from "react-mathjax-preview";

import "./index.css";

class XMarkdown extends Component {
  constructor(props) {
    super(props);
    const {
      data,
      question
    } = props;
    this.state = {
      source: data.text ? data.text : question;
    };
  }
  render() {
    return <MathJax math={this.state.source} />;
  }
}

export default XMarkdown;
```

**Comment by mehdisadeghi** [comment] 2017-11-03 15:45
@Exelenz9 can you create a codepen that reproduces the error or share a link to a page that I can see the complete code?

**Comment by Exelenz9** [comment] 2017-11-04 15:52
@mehdisadeghi Unfortunately, I didn't succeed in doing it. Can you better provide me a simple working example, like this one https://codepen.io/bradleyboy/pen/OPBpGw ?

**Comment by mehdisadeghi** [comment] 2017-11-15 10:39
@Exelenz9 I'll try to make a working codepen when I get some extra time.

**Comment by mehdisadeghi** [comment] 2019-11-12 07:26
Sorry for not comping back to this issue for a very very long time. I'll close this issue since I guess it is a bug outside the component. However, please feel free to reopen this if necessary.

**Closed as completed by mehdisadeghi** 2019-11-12 07:26 UTC
